# -*- mode: ruby -*-
source 'https://rubygems.org'

gem 'bundler'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'


gem 'foundation-rails', '~> 6.1.2.0'
gem 'select2-rails', '~> 4.0.1'
# 'select2-foundation'
gem 'select2-foundation', :git => 'https://github.com/zflat/select2-foundation'

group :development, :test do
  gem 'sqlite3'
  gem "minitest-rails"
  gem 'spring'
end

group :test do
  gem 'minitest-rg', require: false
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
ruby "2.2.0"


